sudo: false

language:
  - android
jdk:
  - oraclejdk8

before_install:
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter platform-tools
  - echo y|android update sdk --all --no-ui --force --filter build-tools-23.0.3
  - echo y|android update sdk --all --no-ui --force --filter android-23

script:
  - ./gradlew build --info